#!/usr/bin/env bash
# ==============================================================================
# gitignore.sh - POSIX Bash script for fetching gitignore.io templates
# ==============================================================================
# - Supports Linux, macOS (BSD), and Git Bash (Windows).
# - Uses mktemp + awk for atomic replacement (avoids sed -i incompatibilities).
# - Preserves the existing file's line endings; new files use UTF-8-compatible bytes and LF.
# ==============================================================================

set -euo pipefail

MARKER_START="# >>> gitignore-generator managed section start >>>"
MARKER_END="# <<< gitignore-generator managed section end <<<"

TARGETS=""
OUTPUT_FILE=".gitignore"
SHOW_LIST=0
NO_BACKUP=0

usage() {
    echo "Usage: $0 [-t targets] [-o output_file] [-l] [-n]"
    echo "  -t targets     Comma-separated gitignore.io targets (e.g. 'python,vscode,windows')"
    echo "  -o output      Output file path (default: .gitignore)"
    echo "  -l             List available gitignore.io templates"
    echo "  -n             No backup"
    exit 1
}

while getopts "t:o:ln" opt; do
    case "$opt" in
        t) TARGETS="$OPTARG" ;;
        o) OUTPUT_FILE="$OPTARG" ;;
        l) SHOW_LIST=1 ;;
        n) NO_BACKUP=1 ;;
        *) usage ;;
    esac
done

# 1. List option
if [ "$SHOW_LIST" -eq 1 ]; then
    echo "[INFO] Fetching template list from gitignore.io..."
    curl -s --max-time 10 "https://www.toptal.com/developers/gitignore/api/list"
    echo ""
    exit 0
fi

# 2. Validate targets
if [ -z "$TARGETS" ]; then
    echo "[ERROR] -t targets argument is required. (e.g., -t 'python,vscode,windows')" >&2
    usage
fi

# Alias mapping
ALIAS_MAP_KEYS=("vscode" "mac" "py" "dotnet" "react" "jetbrains")
ALIAS_MAP_VALS=("visualstudiocode" "macos" "python" "dotnetcore" "reactnative,node" "jetbrains+all")

CLEAN_TARGETS=""
IFS=',' read -ra ADDR <<< "$TARGETS"
for i in "${ADDR[@]}"; do
    t=$(echo "$i" | tr '[:upper:]' '[:lower:]' | xargs)
    matched=0
    for idx in "${!ALIAS_MAP_KEYS[@]}"; do
        if [ "$t" == "${ALIAS_MAP_KEYS[$idx]}" ]; then
            t="${ALIAS_MAP_VALS[$idx]}"
            matched=1
            break
        fi
    done
    if [ -n "$CLEAN_TARGETS" ]; then
        CLEAN_TARGETS="${CLEAN_TARGETS},${t}"
    else
        CLEAN_TARGETS="${t}"
    fi
done

echo "[INFO] Fetching gitignore.io API for targets: $CLEAN_TARGETS"

# 3. Call API
API_URL="https://www.toptal.com/developers/gitignore/api/${CLEAN_TARGETS}"
API_RESP=$(curl -s --max-time 10 "$API_URL" || true)

if [ -z "$API_RESP" ]; then
    echo "[ERROR] Failed to fetch data from API: $API_URL" >&2
    exit 1
fi

# 4. Check for API error
if echo "$API_RESP" | grep -E -q "#!! ERROR:"; then
    echo "[ERROR] gitignore.io API Error detected:" >&2
    echo "$API_RESP" | grep -E "#!! ERROR:" >&2
    exit 1
fi

TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

EOL_STYLE="lf"
if [ -f "$OUTPUT_FILE" ] && LC_ALL=C grep -q $'\r$' "$OUTPUT_FILE"; then
    EOL_STYLE="crlf"
fi

# Create temporary file for managed block
BLOCK_TMP=$(mktemp)
trap 'rm -f "$BLOCK_TMP"' EXIT

{
    echo "$MARKER_START"
    echo "# Generated by gitignore-generator on $TIMESTAMP"
    echo "# Targets: $CLEAN_TARGETS"
    echo "$API_RESP"
    echo "$MARKER_END"
} | tr -d '\r' > "$BLOCK_TMP"
if [ "$EOL_STYLE" = "crlf" ]; then
    awk '{ printf "%s\r\n", $0 }' "$BLOCK_TMP" > "${BLOCK_TMP}.crlf"
    mv "${BLOCK_TMP}.crlf" "$BLOCK_TMP"
fi

# 5. Create backup
if [ -f "$OUTPUT_FILE" ] && [ "$NO_BACKUP" -eq 0 ]; then
    BACKUP_FILE="${OUTPUT_FILE}.bak_$(date +'%Y%m%d_%H%M%S')"
    cp "$OUTPUT_FILE" "$BACKUP_FILE"
    echo "[INFO] Created backup: $BACKUP_FILE"
fi

# 6. Idempotent Merge / Replace
FINAL_TMP=$(mktemp)
trap 'rm -f "$BLOCK_TMP" "$FINAL_TMP"' EXIT

if [ -f "$OUTPUT_FILE" ]; then
    HAS_START=0
    HAS_END=0
    if grep -qF "$MARKER_START" "$OUTPUT_FILE"; then HAS_START=1; fi
    if grep -qF "$MARKER_END" "$OUTPUT_FILE"; then HAS_END=1; fi

    if [ "$HAS_START" -eq 1 ] && [ "$HAS_END" -eq 1 ]; then
        echo "[INFO] Found existing managed section. Replacing block..."
        awk -v block_file="$BLOCK_TMP" -v start_m="$MARKER_START" -v end_m="$MARKER_END" -v style="$EOL_STYLE" '
            BEGIN { skip = 0; ORS = (style == "crlf" ? "\r\n" : "\n") }
            {
                sub(/\r$/, "")
            }
            index($0, start_m) {
                skip = 1
                while ((getline line < block_file) > 0) {
                    sub(/\r$/, "", line)
                    print line
                }
                close(block_file)
                next
            }
            index($0, end_m) {
                skip = 0
                next
            }
            !skip { print }
        ' "$OUTPUT_FILE" > "$FINAL_TMP"
    else
        echo "[INFO] No complete managed block found. Appending to bottom..."
        cp "$OUTPUT_FILE" "$FINAL_TMP"
        # Ensure trailing newline
        if [ -s "$FINAL_TMP" ] && [ "$(tail -c 1 "$FINAL_TMP" | wc -l)" -eq 0 ]; then
            if [ "$EOL_STYLE" = "crlf" ]; then printf '\r\n' >> "$FINAL_TMP"; else printf '\n' >> "$FINAL_TMP"; fi
        fi
        if [ "$EOL_STYLE" = "crlf" ]; then printf '\r\n' >> "$FINAL_TMP"; else printf '\n' >> "$FINAL_TMP"; fi
        cat "$BLOCK_TMP" >> "$FINAL_TMP"
    fi
else
    echo "[INFO] Creating new output file: $OUTPUT_FILE"
    cat "$BLOCK_TMP" > "$FINAL_TMP"
fi

# Move atomic replacement to target output
mv "$FINAL_TMP" "$OUTPUT_FILE"
echo "[SUCCESS] Successfully updated $OUTPUT_FILE"
