<#
.SYNOPSIS
    gitignore.io API를 호출하여 .gitignore 파일을 생성 및 안전하게 병합하는 PowerShell 스크립트.

.DESCRIPTION
    - 기존 UTF-8 인코딩과 주 개행 형식을 보존하고 신규 파일은 UTF-8(BOM 없음), LF로 생성.
    - 마커(# >>> gitignore-generator managed section start >>>) 기반 원등성(Idempotency) 교체 지원.
    - 타임스탬프 기반 백업 생성.

.PARAMETER Targets
    gitignore.io API에 전달할 템플릿 키워드 목록 (콤마 구분). 예: "python,visualstudiocode,windows"

.PARAMETER Output
    생성 또는 병합할 gitignore 파일 경로. 기본값: ".gitignore"

.PARAMETER List
    지원하는 템플릿 목록을 조회하여 콘솔에 출력.

.EXAMPLE
    .\gitignore.ps1 -Targets "python,visualstudiocode,windows"
    .\gitignore.ps1 -Targets "node,jetbrains" -Output ".gitignore"
    .\gitignore.ps1 -List
#>

[CmdletBinding()]
param (
    [Parameter(Position=0)]
    [string]$Targets,

    [Parameter(Position=1)]
    [string]$Output = ".gitignore",

    [switch]$List,

    [switch]$NoBackup
)

$ErrorActionPreference = "Stop"

$MARKER_START = "# >>> gitignore-generator managed section start >>>"
$MARKER_END   = "# <<< gitignore-generator managed section end <<<"

# 1. 지원 템플릿 목록 조회 (-List)
if ($List) {
    Write-Host "[INFO] gitignore.io 템플릿 목록을 가져옵니다..." -ForegroundColor Cyan
    try {
        $listUrl = "https://www.toptal.com/developers/gitignore/api/list"
        $response = Invoke-RestMethod -Uri $listUrl -Method Get -TimeoutSec 10
        Write-Host "`n=== 지원 템플릿 목록 ===" -ForegroundColor Green
        Write-Host $response
        exit 0
    } catch {
        Write-Error "[ERROR] 템플릿 목록을 가져오는 중 오류가 발생했습니다: $_"
        exit 1
    }
}

# 2. Targets 인수 검증
if ([string]::IsNullOrWhiteSpace($Targets)) {
    Write-Error "[ERROR] -Targets 인수가 필요합니다. (예: -Targets 'python,visualstudiocode,windows' 또는 -List)"
    exit 1
}

# 별칭(Alias) 매핑 처리
$aliasMap = @{
    "vscode"   = "visualstudiocode"
    "mac"      = "macos"
    "py"       = "python"
    "dotnet"   = "dotnetcore"
    "react"    = "reactnative,node"
    "jetbrains"= "jetbrains+all"
}

$targetList = $Targets.Split(',') | ForEach-Object {
    $t = $_.Trim().ToLower()
    if ($aliasMap.ContainsKey($t)) {
        $aliasMap[$t]
    } else {
        $t
    }
}
$cleanTargets = ($targetList -join ",").Trim(',')

Write-Host "[INFO] gitignore.io API 요청 중... (Targets: $cleanTargets)" -ForegroundColor Cyan

# 3. API 호출
$apiUrl = "https://www.toptal.com/developers/gitignore/api/$cleanTargets"
try {
    $webClient = New-Object System.Net.WebClient
    $webClient.Encoding = [System.Text.Encoding]::UTF8
    $apiResponse = $webClient.DownloadString($apiUrl)
} catch {
    Write-Error "[ERROR] API 호출 실패 ($apiUrl): $_"
    exit 1
}

# 4. API 에러 응답 파싱 (#!! ERROR: 검사)
if ($apiResponse -match "#!! ERROR:\s*(.+) is undefined") {
    $invalidKey = $Matches[1]
    Write-Error "[ERROR] gitignore.io API 오류: '$invalidKey' 템플릿은 존재하지 않습니다. (-List 옵션으로 확인하세요)"
    exit 1
}

# 5. Managed Block 구성 (신규 파일 기본 LF 개행)
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$managedBlock = @"
$MARKER_START
# Generated by gitignore-generator on $timestamp
# Targets: $cleanTargets
$apiResponse
$MARKER_END
"@ -replace "`r`n", "`n"

$targetPath = [System.IO.Path]::GetFullPath($Output)

# 6. 백업 생성
if ((Test-Path $targetPath) -and (-not $NoBackup)) {
    $dateStr = Get-Date -Format "yyyyMMdd_HHmmss"
    $backupPath = "${targetPath}.bak_${dateStr}"
    Copy-Item -Path $targetPath -Destination $backupPath -Force
    Write-Host "[INFO] 기존 파일 백업 완료: $backupPath" -ForegroundColor Yellow
}

# 7. 마커 기반 원등성 병합/교체 로직
$utf8StrictNoBom = New-Object System.Text.UTF8Encoding($false, $true)
$writeBom = $false
$newline = "`n"

if (Test-Path $targetPath) {
    $existingBytes = [System.IO.File]::ReadAllBytes($targetPath)
    $offset = 0
    if ($existingBytes.Length -ge 3 -and $existingBytes[0] -eq 0xEF -and $existingBytes[1] -eq 0xBB -and $existingBytes[2] -eq 0xBF) {
        $writeBom = $true
        $offset = 3
    }
    try {
        $existingText = $utf8StrictNoBom.GetString($existingBytes, $offset, $existingBytes.Length - $offset)
    } catch {
        throw "기존 파일의 인코딩을 안전하게 보존할 수 없습니다. UTF-8 파일만 지원합니다: $targetPath"
    }
    if ($existingText.Contains("`r`n")) {
        $newline = "`r`n"
    }
    $managedBlockForFile = $managedBlock -replace "`n", $newline

    $startIndex = $existingText.IndexOf($MARKER_START)
    $endIndex   = $existingText.IndexOf($MARKER_END)

    if ($startIndex -ge 0 -and $endIndex -gt $startIndex) {
        # 시작 마커와 종료 마커가 모두 정상 존재하는 경우 -> 해당 구간 수술적 교체
        Write-Host "[INFO] 기존 managed section을 발견하였습니다. 구역을 교체합니다." -ForegroundColor Green
        
        $before = $existingText.Substring(0, $startIndex)
        $after  = $existingText.Substring($endIndex + $MARKER_END.Length)
        
        $finalContent = $before + $managedBlockForFile + $after
    } else {
        # 마커가 없거나 손상된 경우 -> 하단에 Append
        Write-Host "[INFO] 기존 파일에 마커 구역이 없어 하단에 새 구역을 추가합니다." -ForegroundColor Green
        
        $prefix = ""
        if (-not $existingText.EndsWith("`n") -and $existingText.Length -gt 0) {
            $prefix = $newline
        }
        $finalContent = $existingText + $prefix + $newline + $managedBlockForFile
    }
} else {
    # 신규 파일 생성
    Write-Host "[INFO] 신규 .gitignore 파일을 생성합니다: $targetPath" -ForegroundColor Green
    $finalContent = $managedBlock
}

# 8. 기존 UTF-8 BOM 여부와 개행을 보존하여 저장
$contentBytes = $utf8StrictNoBom.GetBytes($finalContent)
if ($writeBom) {
    $preamble = [System.Text.Encoding]::UTF8.GetPreamble()
    $outputBytes = New-Object byte[] ($preamble.Length + $contentBytes.Length)
    [System.Array]::Copy($preamble, 0, $outputBytes, 0, $preamble.Length)
    [System.Array]::Copy($contentBytes, 0, $outputBytes, $preamble.Length, $contentBytes.Length)
} else {
    $outputBytes = $contentBytes
}
[System.IO.File]::WriteAllBytes($targetPath, $outputBytes)

Write-Host "[SUCCESS] .gitignore 생성이 성공적으로 완료되었습니다!" -ForegroundColor Green
